<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use common\models\user\User;
use yii\web\Response;

class BasicController extends Controller
{
    /**
     * Сообщение об ошибке
     *
     * @var
     */
    public $msg;
    /**
     * Наличие ошибки
     *
     * @var
     */
    public $error;

    /**
     * Код ошибки
     *
     * @var int
     */
    public $error_type = 0;

    /**
     * Данные к выдаче
     *
     * @var
     */
    public $data;

    /**
     * Объект хранения сессии
     *
     * @var
     */
    public $session;

    /**
     * Инфициализируем базовый параметры (свойства контроллеров)
     */
    public function basic_param()
    {
        if (isset(Yii::$app->session)   ) {
            $this->session = Yii::$app->session;
            if (!$this->session->isActive) {
                $this->session->open();
            }
        }
    }

    public function init()
    {

        $this->basic_param();
        parent::init(); // TODO: Change the autogenerated stub
    }


    //---------------------------------------------------- AJAX ----------------------------------------//
    /**
     * Стандартная выдача сообщений
     *
     * @return array
     */
    public function out()
    {
        return ['error'=>$this->error, $this->error_type,'msg'=>$this->msg, 'data'=> ($this->error=='no') ? $this->data : '' ];
    }

    /**
     * Базовая инициализация
     */
    public function init_ajax()
    {
        $this->error = 'yes';
        $this->msg = Yii::$app->params['messages']['user']['error']['params'];
        Yii::$app->response->format = Response::FORMAT_JSON;
    }
    //---------------------------------------------------- END AJAX ----------------------------------------//
}
